In [3]:
import numpy as np
import matplotlib.pyplot as plt

from helpers import load_csv_data
from preprocessing_naive import preprocessing_dataset_naive



In [4]:
# take x_train
_, data, _, _, _, _ = load_csv_data("data/dataset")

In [39]:
def pca(data):
    #preprocessing
    data,_,_ = preprocessing_dataset_naive(data)
    print(data[0:5, 0:5])
    # compute the mean of each column
    mean = np.mean(data, axis=0)
    mean_data = data - mean
    # compute the covariance matrix
    cov = np.cov(mean_data,rowvar=False)
    cov = np.round(cov, 2)
    

    # compute the eigenvalues and eigenvectors
    eig_val, eig_vec = np.linalg.eig(cov)
    # sort the eigenvalues and eigenvectors
    idx = np.arange(0, len(eig_val), 1)
    idx = ([x for _, x in sorted(zip(eig_val, idx))])[::-1]
    eig_val = eig_val
    eig_vec = eig_vec[:, idx]
    print("eig_vec",eig_vec.shape)
    # compute the explained variance
    exp_var = eig_val/np.sum(eig_val)
    # compute the cumulative explained variance
    cum_exp_var = np.cumsum(exp_var)
    #get the index of the first value above 99%
    index = np.argmax(cum_exp_var > 0.99)
    #get the number of components
    n_components = index + 1
    #get the components
    components = eig_vec[:, :n_components]
    #transform the data
    transformed_data = np.dot(mean_data, components)
    return transformed_data


In [40]:
#preprocess the data
#preprocessed_data = preprocessing_dataset_naive(data)
# transform the data
transformed_data = pca(data)
print(transformed_data.shape)
print(transformed_data)


[[ 0.          0.          0.76296172 -0.43468716  0.03911607]
 [ 0.          0.         -1.17385332 -0.43468716 -0.91810303]
 [ 0.          0.          0.76296172 -0.43468716  0.99633516]
 [-1.2393456   0.          0.76296172  2.46554605 -0.91810303]
 [ 0.          0.          0.76296172  1.49880165  5.78243063]]
eig_vec (200, 200)
(328135, 153)
[[-1.98171095e+00 -1.29503340e+00  5.61669076e-01 ...  5.78109230e-02
   2.77736822e-01 -5.12246900e-02]
 [ 1.13338415e+01  1.77676370e+00  1.18043819e+00 ... -2.11517002e-01
   2.44608145e-01  7.91490673e-01]
 [-1.28527453e+00  1.77126194e+00  9.57880452e-01 ...  1.86845868e-02
  -9.42054004e-03  4.08204365e-03]
 ...
 [-1.29516669e+00  1.83828225e+00 -6.05018382e-01 ...  5.40081924e-02
  -3.30124961e-02 -2.24808398e-02]
 [-1.04260517e+00 -7.85211190e-01 -3.00544533e-01 ... -1.19969187e-01
   7.30660500e-02  5.81197302e-02]
 [ 2.11055003e+00 -3.04329763e-01  1.54573220e+00 ... -1.72350496e-01
   9.19695055e-02  7.66789124e-03]]
